[package]
name = "stylist-core"
version = "0.7.0"
license = "MIT"
repository = "https://github.com/futursolo/stylist-rs"
authors = [
    "Kaede Hoshiakwa <futursolo@icloud.com>",
    "Martin Molzer <ga65guy@mytum.de>",
]
edition = "2018"
description = "Stylist is a CSS-in-Rust styling solution for WebAssembly Applications."
keywords = [
    "CSS",
    "web",
    "css-in-rust",
    "yew"
]
categories = ["wasm", "web-programming"]
readme = "README.md"
homepage = "https://github.com/futursolo/stylist-rs"

[dev-dependencies]
log = "0.4"
env_logger = "0.9"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.24"
