[package]
name = "stylist-core"
version = "0.7.0"
license = "MIT"
repository = "https://github.com/futursolo/stylist-rs"
authors = [
    "Kaede Hoshiakwa <futursolo@icloud.com>",
    "Martin Molzer <ga65guy@mytum.de>",
]
edition = "2018"
description = "Stylist is a CSS-in-Rust styling solution for WebAssembly Applications."
keywords = [
    "CSS",
    "web",
    "css-in-rust",
    "yew"
]
categories = ["wasm", "web-programming"]
readme = "README.md"
homepage = "https://github.com/futursolo/stylist-rs"

[dependencies]
once_cell = "1.8.0"
yew = { version = "0.18.0", optional = true, default-features = false, features = ["web_sys"] }
rand = { version = "0.8.4", features = ["small_rng"] }

[dev-dependencies]
log = "0.4"
env_logger = "0.9"

[dependencies.web-sys]
version = "0.3.51"
features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlHeadElement",
    "HtmlStyleElement",
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.3", features = ["js"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.24"

[features]
default = []
yew_integration = ["yew"]

[package.metadata.docs.rs]
features = ["yew_integration"]
all-features = true
