[package]
name = "stylist"
version = "0.8.0"
license = "MIT"
repository = "https://github.com/futursolo/stylist-rs"
authors = [
    "Kaede Hoshiakwa <futursolo@icloud.com>",
    "Martin Molzer <ga65guy@mytum.de>",
]
edition = "2018"
description = "Stylist is a CSS-in-Rust styling solution for WebAssembly Applications."
keywords = [
    "CSS",
    "web",
    "css-in-rust",
    "yew"
]
categories = ["wasm", "web-programming"]
readme = "../../README.md"
homepage = "https://github.com/futursolo/stylist-rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
once_cell = "1.8.0"
rand = { version = "0.8.4", features = ["small_rng"] }
stylist-core = { path = "../stylist-core", version = "0.8.0" }
wasm-bindgen = "0.2.74"
yew = { version = "0.18.0", optional = true, default-features = false, features = ["web_sys"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.3", features = ["js"] }
web-sys = { version = "0.3.51", features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlHeadElement",
    "HtmlStyleElement",
] }

[dev-dependencies]
log = "0.4"
env_logger = "0.9"

[features]
default = []
yew_integration = ["yew"]

[package.metadata.docs.rs]
features = ["yew_integration"]
all-features = true
rustdoc-args = ["--cfg", "documenting"]
