[package]
name = "yew-shadow"
version = "0.1.0"
authors = ["Kaede Hoshikawa <futursolo@icloud.com>"]
edition = "2018"

[dependencies]
log = "0.4"
console_log = { version = "0.2.0", features = ["color"] }
yew = { version = "0.18.0" }
stylist = { path = "../../packages/stylist", features = ["yew_integration", "style_manager"] }
once_cell = "1"

[dependencies.web-sys]
version = "0.3.51"
features = [
    "Window",
    "Document",
    "Element",
    "ShadowRoot",
    "ShadowRootInit",
    "ShadowRootMode",
]
