[package]
name = "css-in-rust"
version = "0.0.1"
license = "MIT"
authors = ["Lukas Wagner <appdev.lukaswagner@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "^0.2.59"
nom = "^5.1.1"
rand = { version = "^0.7", features = ["wasm-bindgen", "small_rng"] }
yew = { version = "^0.13", features = ["web_sys"] }
lazy_static = "^1.4.0"

[dependencies.web-sys]
version = "^0.3"
features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlHeadElement",
    "HtmlStyleElement",
]
