[workspace]
members = [
    "packages/stylist",
    "packages/stylist-core",
    "packages/stylist-parser",
    "packages/stylist-macros",

    "examples/benchmarks",
    "examples/proc-macros",
    "examples/yew-integration",
    "examples/yew-shadow",
    "examples/yew-theme-agent",
    "examples/yew-theme-yewdux",
]
