[package]
name = "stylist-rs"
version = "0.6.0"
license = "MIT"
repository = "https://github.com/futursolo/stylist-rs"
authors = [
    "Kaede Hoshiakwa <futursolo@icloud.com>",
]
edition = "2018"
description = "Stylist is a CSS-in-Rust styling solution for WebAssembly Applications."
keywords = [
    "CSS",
    "web",
    "css-in-rust",
    "seed",
    "yew"
]
categories = ["wasm", "web-programming"]
readme = "README.md"
homepage = "https://github.com/futursolo/stylist-rs"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nom = "6.2.1"
once_cell = "1.8.0"
yew = { version = "0.18.0", optional = true }
rand = { version = "0.8.4", features = ["small_rng"] }

[dependencies.web-sys]
version = "0.3.51"
features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlHeadElement",
    "HtmlStyleElement",
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.74"
getrandom = { version = "0.2.3", features = ["js"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.24"

[package.metadata.docs.rs]
features = ["yew"]
