[package]
name = "yew_integration"
version = "0.0.1"
authors = ["Kaede Hoshikawa <futursolo@icloud.com>"]
edition = "2018"

[dependencies]
log = "0.4"
web_logger = "0.2"
yew = {version = "0.18.0"}
stylist = { path = "../..", features = ["yew"] }
